#!/usr/bin/env bash
set -e

EXPORT_DIR="omar-premium-panel-export"
rm -rf "$EXPORT_DIR"
mkdir -p "$EXPORT_DIR"
mkdir -p "$EXPORT_DIR/api/_lib"
mkdir -p "$EXPORT_DIR/src/pages"
mkdir -p "$EXPORT_DIR/src/lib"
mkdir -p "$EXPORT_DIR/src/components/panel"
mkdir -p "$EXPORT_DIR/src/components/ui"
mkdir -p "$EXPORT_DIR/src/hooks"

copy() {
  local src="$1"
  local dest="$EXPORT_DIR/$1"
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
}

copy "package.json"
copy "vercel.json"
copy "vite.config.ts"
copy "index.html"
copy "postcss.config.js"
copy "tailwind.config.ts"
copy "components.json"
copy "tsconfig.json"
copy "tsconfig.app.json"
copy "tsconfig.node.json"
copy "eslint.config.js"
copy "src/App.tsx"
copy "src/main.tsx"
copy "src/globals.css"
copy "src/App.css"
copy "src/vite-env.d.ts"
copy "src/pages/Index.tsx"
copy "src/pages/NotFound.tsx"
copy "src/lib/panel-api.ts"
copy "src/lib/utils.ts"
copy "src/components/panel/add-stream-dialog.tsx"
copy "src/components/panel/add-user-dialog.tsx"
copy "src/components/panel/settings-card.tsx"
copy "src/components/panel/stats-card.tsx"
copy "src/components/ui/badge.tsx"
copy "src/components/ui/button.tsx"
copy "src/components/ui/card.tsx"
copy "src/components/ui/dialog.tsx"
copy "src/components/ui/input.tsx"
copy "src/components/ui/label.tsx"
copy "src/components/ui/table.tsx"
copy "src/components/ui/textarea.tsx"
copy "src/components/ui/toast.tsx"
copy "src/components/ui/toaster.tsx"
copy "src/components/ui/sonner.tsx"
copy "src/components/ui/tooltip.tsx"
copy "src/hooks/use-toast.ts"
copy "api/_lib/supabase.ts"
copy "api/admin-panel.ts"
copy "api/get.ts"
copy "api/player-api.ts"
copy "api/xmltv.ts"
copy "api/live-proxy.ts"

echo "Exported current OMAR PREMIUM PANEL files to: $EXPORT_DIR"
