-- OMAR PREMIUM PANEL - IBO database handoff snapshot
-- Generated as a developer handoff document.
-- This file documents the IBO-specific schema and functions currently expected by the app.
-- It is NOT a generated Supabase migration file.

-- =========================================================
-- TABLES
-- =========================================================

CREATE TABLE IF NOT EXISTS public.ibo_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  duration_days integer NOT NULL DEFAULT 30,
  max_connections integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'Active',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ibo_user_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.iptv_users(id) ON DELETE CASCADE,
  package_id bigint REFERENCES public.ibo_packages(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'Active',
  expiry_date date,
  max_connections integer NOT NULL DEFAULT 1,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ibo_user_subscriptions_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.ibo_devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mac_address text NOT NULL,
  device_key text NOT NULL,
  user_id uuid REFERENCES public.iptv_users(id) ON DELETE SET NULL,
  package_id bigint REFERENCES public.ibo_packages(id) ON DELETE SET NULL,
  expiry_date date,
  status text NOT NULL DEFAULT 'Active',
  last_seen timestamptz,
  last_ip text,
  location text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ibo_package_live_streams (
  package_id bigint NOT NULL REFERENCES public.ibo_packages(id) ON DELETE CASCADE,
  live_stream_id bigint NOT NULL REFERENCES public.live_streams(id) ON DELETE CASCADE,
  PRIMARY KEY (package_id, live_stream_id)
);

CREATE TABLE IF NOT EXISTS public.ibo_package_vod_streams (
  package_id bigint NOT NULL REFERENCES public.ibo_packages(id) ON DELETE CASCADE,
  vod_stream_id bigint NOT NULL REFERENCES public.vod_streams(id) ON DELETE CASCADE,
  PRIMARY KEY (package_id, vod_stream_id)
);

CREATE TABLE IF NOT EXISTS public.ibo_package_series (
  package_id bigint NOT NULL REFERENCES public.ibo_packages(id) ON DELETE CASCADE,
  series_id bigint NOT NULL REFERENCES public.series(id) ON DELETE CASCADE,
  PRIMARY KEY (package_id, series_id)
);

CREATE TABLE IF NOT EXISTS public.ibo_settings (
  key text PRIMARY KEY,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ibo_activity_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ibo_playlists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.iptv_users(id) ON DELETE CASCADE,
  username text NOT NULL,
  bucket_name text NOT NULL DEFAULT 'playlists',
  storage_path text NOT NULL,
  public_url text NOT NULL,
  channel_count integer NOT NULL DEFAULT 0,
  generated_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ibo_playlists_username_key UNIQUE (username)
);

ALTER TABLE public.ibo_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_package_live_streams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_package_vod_streams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_package_series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ibo_playlists ENABLE ROW LEVEL SECURITY;

-- NOTE:
-- At handoff time, no explicit pg_policies rows were found for the IBO tables.
-- The app currently relies on SECURITY DEFINER functions and service-role usage in edge functions.

-- =========================================================
-- IBO-SPECIFIC DATABASE FUNCTIONS
-- =========================================================

CREATE OR REPLACE FUNCTION public.ibo_log_activity(p_action text, p_entity_type text, p_entity_id text, p_message text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.ibo_activity_logs (action, entity_type, entity_id, message)
  VALUES (COALESCE(p_action, ''), COALESCE(p_entity_type, ''), p_entity_id, COALESCE(p_message, ''));
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_delete_ibo_device(p_username text, p_password text, p_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  device_mac text;
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  SELECT mac_address INTO device_mac FROM public.ibo_devices WHERE id = p_id;
  DELETE FROM public.ibo_devices WHERE id = p_id;

  PERFORM public.ibo_log_activity('delete', 'device', p_id::text, 'IBO device ' || COALESCE(device_mac, p_id::text) || ' deleted');

  RETURN jsonb_build_object('success', true, 'id', p_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_delete_ibo_package(p_username text, p_password text, p_id bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  package_name text;
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  SELECT name INTO package_name FROM public.ibo_packages WHERE id = p_id;
  DELETE FROM public.ibo_packages WHERE id = p_id;

  PERFORM public.ibo_log_activity('delete', 'package', p_id::text, 'IBO package ' || COALESCE(package_name, p_id::text) || ' deleted');

  RETURN jsonb_build_object('success', true, 'id', p_id);
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_list_ibo_playlists(p_username text, p_password text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  RETURN COALESCE(
    (
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'user_id', p.user_id,
          'username', p.username,
          'bucket_name', p.bucket_name,
          'storage_path', p.storage_path,
          'public_url', p.public_url,
          'channel_count', p.channel_count,
          'generated_at', p.generated_at,
          'updated_at', p.updated_at
        )
        ORDER BY p.generated_at DESC, p.username ASC
      )
      FROM public.ibo_playlists p
    ),
    '[]'::jsonb
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_save_ibo_device(p_username text, p_password text, p_id uuid DEFAULT NULL::uuid, p_mac_address text DEFAULT ''::text, p_device_key text DEFAULT ''::text, p_user_id uuid DEFAULT NULL::uuid, p_package_id bigint DEFAULT NULL::bigint, p_status text DEFAULT 'Active'::text, p_expiry_date date DEFAULT NULL::date, p_last_seen timestamp with time zone DEFAULT NULL::timestamp with time zone, p_last_ip text DEFAULT ''::text, p_location text DEFAULT ''::text, p_notes text DEFAULT ''::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  record_data public.ibo_devices;
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  IF p_id IS NULL THEN
    INSERT INTO public.ibo_devices (
      mac_address,
      device_key,
      user_id,
      package_id,
      status,
      expiry_date,
      last_seen,
      last_ip,
      location,
      notes,
      updated_at
    )
    VALUES (
      upper(trim(p_mac_address)),
      trim(p_device_key),
      p_user_id,
      p_package_id,
      CASE WHEN p_status IN ('Blocked', 'Expired', 'Disabled') THEN p_status ELSE 'Active' END,
      p_expiry_date,
      p_last_seen,
      NULLIF(trim(COALESCE(p_last_ip, '')), ''),
      NULLIF(trim(COALESCE(p_location, '')), ''),
      NULLIF(trim(COALESCE(p_notes, '')), ''),
      now()
    )
    RETURNING * INTO record_data;
  ELSE
    UPDATE public.ibo_devices
    SET
      mac_address = upper(trim(p_mac_address)),
      device_key = trim(p_device_key),
      user_id = p_user_id,
      package_id = p_package_id,
      status = CASE WHEN p_status IN ('Blocked', 'Expired', 'Disabled') THEN p_status ELSE 'Active' END,
      expiry_date = p_expiry_date,
      last_seen = p_last_seen,
      last_ip = NULLIF(trim(COALESCE(p_last_ip, '')), ''),
      location = NULLIF(trim(COALESCE(p_location, '')), ''),
      notes = NULLIF(trim(COALESCE(p_notes, '')), ''),
      updated_at = now()
    WHERE id = p_id
    RETURNING * INTO record_data;
  END IF;

  PERFORM public.ibo_log_activity(
    CASE WHEN p_id IS NULL THEN 'create' ELSE 'update' END,
    'device',
    record_data.id::text,
    'IBO device ' || record_data.mac_address || ' saved'
  );

  RETURN jsonb_build_object(
    'id', record_data.id,
    'mac_address', record_data.mac_address,
    'device_key', record_data.device_key,
    'user_id', record_data.user_id,
    'package_id', record_data.package_id,
    'status', record_data.status,
    'expiry_date', record_data.expiry_date,
    'last_seen', record_data.last_seen,
    'last_ip', record_data.last_ip,
    'location', record_data.location,
    'notes', record_data.notes,
    'created_at', record_data.created_at,
    'updated_at', record_data.updated_at
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_save_ibo_package(p_username text, p_password text, p_id bigint DEFAULT NULL::bigint, p_name text DEFAULT ''::text, p_description text DEFAULT ''::text, p_duration_days integer DEFAULT 30, p_max_connections integer DEFAULT 1, p_status text DEFAULT 'Active'::text, p_notes text DEFAULT ''::text, p_live_stream_ids jsonb DEFAULT '[]'::jsonb, p_vod_stream_ids jsonb DEFAULT '[]'::jsonb, p_series_ids jsonb DEFAULT '[]'::jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  record_data public.ibo_packages;
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  IF p_id IS NULL OR p_id = 0 THEN
    INSERT INTO public.ibo_packages (name, description, duration_days, max_connections, status, notes, updated_at)
    VALUES (
      trim(p_name),
      NULLIF(trim(COALESCE(p_description, '')), ''),
      GREATEST(COALESCE(p_duration_days, 30), 1),
      GREATEST(COALESCE(p_max_connections, 1), 1),
      CASE WHEN p_status = 'Disabled' THEN 'Disabled' ELSE 'Active' END,
      NULLIF(trim(COALESCE(p_notes, '')), ''),
      now()
    )
    RETURNING * INTO record_data;
  ELSE
    UPDATE public.ibo_packages
    SET
      name = trim(p_name),
      description = NULLIF(trim(COALESCE(p_description, '')), ''),
      duration_days = GREATEST(COALESCE(p_duration_days, 30), 1),
      max_connections = GREATEST(COALESCE(p_max_connections, 1), 1),
      status = CASE WHEN p_status = 'Disabled' THEN 'Disabled' ELSE 'Active' END,
      notes = NULLIF(trim(COALESCE(p_notes, '')), ''),
      updated_at = now()
    WHERE id = p_id
    RETURNING * INTO record_data;
  END IF;

  DELETE FROM public.ibo_package_live_streams WHERE package_id = record_data.id;
  INSERT INTO public.ibo_package_live_streams (package_id, live_stream_id)
  SELECT record_data.id, value::bigint
  FROM jsonb_array_elements_text(COALESCE(p_live_stream_ids, '[]'::jsonb));

  DELETE FROM public.ibo_package_vod_streams WHERE package_id = record_data.id;
  INSERT INTO public.ibo_package_vod_streams (package_id, vod_stream_id)
  SELECT record_data.id, value::bigint
  FROM jsonb_array_elements_text(COALESCE(p_vod_stream_ids, '[]'::jsonb));

  DELETE FROM public.ibo_package_series WHERE package_id = record_data.id;
  INSERT INTO public.ibo_package_series (package_id, series_id)
  SELECT record_data.id, value::bigint
  FROM jsonb_array_elements_text(COALESCE(p_series_ids, '[]'::jsonb));

  PERFORM public.ibo_log_activity(
    CASE WHEN p_id IS NULL OR p_id = 0 THEN 'create' ELSE 'update' END,
    'package',
    record_data.id::text,
    'IBO package ' || record_data.name || ' saved'
  );

  RETURN jsonb_build_object(
    'id', record_data.id,
    'name', record_data.name,
    'description', record_data.description,
    'duration_days', record_data.duration_days,
    'max_connections', record_data.max_connections,
    'status', record_data.status,
    'notes', record_data.notes,
    'created_at', record_data.created_at,
    'updated_at', record_data.updated_at
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_save_ibo_settings(p_username text, p_password text, p_app_name text DEFAULT 'OMAR IBO PANEL'::text, p_logo_url text DEFAULT ''::text, p_api_base_url text DEFAULT ''::text, p_default_epg_url text DEFAULT ''::text, p_theme_mode text DEFAULT 'system'::text, p_primary_color text DEFAULT '#6D4CFF'::text, p_secondary_color text DEFAULT '#1ec8a5'::text, p_maintenance_mode boolean DEFAULT false, p_notifications_enabled boolean DEFAULT true)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('app_name', COALESCE(p_app_name, 'OMAR IBO PANEL'), now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('logo_url', COALESCE(p_logo_url, ''), now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('api_base_url', COALESCE(p_api_base_url, ''), now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('default_epg_url', COALESCE(p_default_epg_url, ''), now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('theme_mode', COALESCE(p_theme_mode, 'system'), now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('primary_color', COALESCE(p_primary_color, '#6D4CFF'), now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('secondary_color', COALESCE(p_secondary_color, '#1ec8a5'), now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('maintenance_mode', CASE WHEN p_maintenance_mode THEN 'true' ELSE 'false' END, now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
  INSERT INTO public.ibo_settings (key, value, updated_at) VALUES ('notifications_enabled', CASE WHEN p_notifications_enabled THEN 'true' ELSE 'false' END, now()) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now();

  PERFORM public.ibo_log_activity('update', 'settings', null, 'IBO settings updated');

  RETURN jsonb_build_object(
    'app_name', COALESCE(p_app_name, 'OMAR IBO PANEL'),
    'logo_url', COALESCE(p_logo_url, ''),
    'api_base_url', COALESCE(p_api_base_url, ''),
    'default_epg_url', COALESCE(p_default_epg_url, ''),
    'theme_mode', COALESCE(p_theme_mode, 'system'),
    'primary_color', COALESCE(p_primary_color, '#6D4CFF'),
    'secondary_color', COALESCE(p_secondary_color, '#1ec8a5'),
    'maintenance_mode', COALESCE(p_maintenance_mode, false),
    'notifications_enabled', COALESCE(p_notifications_enabled, true)
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_save_ibo_user(p_username text, p_password text, p_user_id uuid, p_account_status text DEFAULT 'Active'::text, p_expiry_date date DEFAULT NULL::date, p_max_connections integer DEFAULT 1, p_notes text DEFAULT ''::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  record_data public.iptv_users;
  mapped_status text;
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  mapped_status := CASE
    WHEN p_account_status = 'Blocked' THEN 'Banned'
    WHEN p_account_status = 'Expired' THEN 'Expired'
    ELSE 'Active'
  END;

  UPDATE public.iptv_users
  SET
    status = mapped_status,
    expiry_date = COALESCE(p_expiry_date, expiry_date),
    max_connections = GREATEST(COALESCE(p_max_connections, max_connections), 1),
    notes = NULLIF(trim(COALESCE(p_notes, '')), ''),
    updated_at = now()
  WHERE id = p_user_id
  RETURNING * INTO record_data;

  PERFORM public.ibo_log_activity('update', 'user', record_data.id::text, 'IBO user ' || record_data.username || ' updated');

  RETURN jsonb_build_object(
    'id', record_data.id,
    'username', record_data.username,
    'status', CASE WHEN record_data.status = 'Banned' THEN 'Blocked' ELSE record_data.status END,
    'expiry_date', record_data.expiry_date,
    'max_connections', record_data.max_connections,
    'notes', record_data.notes,
    'created_at', record_data.created_at,
    'updated_at', record_data.updated_at
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_save_ibo_user_subscription(p_username text, p_password text, p_user_id uuid, p_package_id bigint DEFAULT NULL::bigint, p_status text DEFAULT 'Active'::text, p_expiry_date date DEFAULT NULL::date, p_max_connections integer DEFAULT 1, p_notes text DEFAULT ''::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  record_data public.ibo_user_subscriptions;
  mapped_user_status text;
  target_username text;
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  mapped_user_status := CASE
    WHEN p_status = 'Blocked' THEN 'Banned'
    WHEN p_status = 'Expired' THEN 'Expired'
    ELSE 'Active'
  END;

  INSERT INTO public.ibo_user_subscriptions (user_id, package_id, status, expiry_date, max_connections, notes, updated_at)
  VALUES (
    p_user_id,
    p_package_id,
    CASE WHEN p_status IN ('Blocked', 'Expired', 'Disabled') THEN p_status ELSE 'Active' END,
    p_expiry_date,
    GREATEST(COALESCE(p_max_connections, 1), 1),
    NULLIF(trim(COALESCE(p_notes, '')), ''),
    now()
  )
  ON CONFLICT (user_id)
  DO UPDATE SET
    package_id = EXCLUDED.package_id,
    status = EXCLUDED.status,
    expiry_date = EXCLUDED.expiry_date,
    max_connections = EXCLUDED.max_connections,
    notes = EXCLUDED.notes,
    updated_at = now()
  RETURNING * INTO record_data;

  UPDATE public.iptv_users
  SET
    expiry_date = COALESCE(p_expiry_date, expiry_date),
    max_connections = GREATEST(COALESCE(p_max_connections, max_connections), 1),
    status = mapped_user_status,
    updated_at = now()
  WHERE id = p_user_id;

  SELECT username INTO target_username FROM public.iptv_users WHERE id = p_user_id;

  PERFORM public.ibo_log_activity('save', 'subscription', record_data.id::text, 'IBO subscription saved for user ' || COALESCE(target_username, p_user_id::text));

  RETURN jsonb_build_object(
    'id', record_data.id,
    'user_id', record_data.user_id,
    'package_id', record_data.package_id,
    'status', record_data.status,
    'expiry_date', record_data.expiry_date,
    'max_connections', record_data.max_connections,
    'notes', record_data.notes,
    'created_at', record_data.created_at,
    'updated_at', record_data.updated_at
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_ibo_panel_data(p_username text, p_password text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  settings_map jsonb;
BEGIN
  PERFORM public.assert_admin_auth(p_username, p_password);

  SELECT COALESCE(jsonb_object_agg(key, value), '{}'::jsonb)
  INTO settings_map
  FROM public.ibo_settings;

  RETURN jsonb_build_object(
    'counts', jsonb_build_object(
      'devices', (SELECT COUNT(*) FROM public.ibo_devices),
      'active_devices', (SELECT COUNT(*) FROM public.ibo_devices WHERE status = 'Active'),
      'expired_devices', (SELECT COUNT(*) FROM public.ibo_devices WHERE status = 'Expired'),
      'blocked_devices', (SELECT COUNT(*) FROM public.ibo_devices WHERE status = 'Blocked'),
      'connected_users', (SELECT COUNT(DISTINCT user_id) FROM public.ibo_devices WHERE user_id IS NOT NULL AND status = 'Active'),
      'packages', (SELECT COUNT(*) FROM public.ibo_packages),
      'channels', (SELECT COUNT(*) FROM public.live_streams WHERE status = 'Active'),
      'movies', (SELECT COUNT(*) FROM public.vod_streams WHERE status = 'Active'),
      'series', (SELECT COUNT(*) FROM public.series WHERE status = 'Active')
    ),
    'devices', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', d.id,
          'mac_address', d.mac_address,
          'device_key', d.device_key,
          'user_id', d.user_id,
          'username', u.username,
          'package_id', d.package_id,
          'package_name', p.name,
          'expiry_date', d.expiry_date,
          'status', d.status,
          'last_seen', d.last_seen,
          'last_ip', d.last_ip,
          'location', d.location,
          'notes', d.notes,
          'created_at', d.created_at,
          'updated_at', d.updated_at
        )
        ORDER BY d.created_at DESC
      )
      FROM public.ibo_devices d
      LEFT JOIN public.iptv_users u ON u.id = d.user_id
      LEFT JOIN public.ibo_packages p ON p.id = d.package_id
    ), '[]'::jsonb),
    'packages', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'name', p.name,
          'description', p.description,
          'duration_days', p.duration_days,
          'max_connections', p.max_connections,
          'status', p.status,
          'notes', p.notes,
          'created_at', p.created_at,
          'updated_at', p.updated_at,
          'user_count', (SELECT COUNT(*) FROM public.ibo_user_subscriptions s WHERE s.package_id = p.id),
          'device_count', (SELECT COUNT(*) FROM public.ibo_devices d WHERE d.package_id = p.id),
          'live_stream_ids', COALESCE((SELECT jsonb_agg(m.live_stream_id ORDER BY m.live_stream_id) FROM public.ibo_package_live_streams m WHERE m.package_id = p.id), '[]'::jsonb),
          'vod_stream_ids', COALESCE((SELECT jsonb_agg(m.vod_stream_id ORDER BY m.vod_stream_id) FROM public.ibo_package_vod_streams m WHERE m.package_id = p.id), '[]'::jsonb),
          'series_ids', COALESCE((SELECT jsonb_agg(m.series_id ORDER BY m.series_id) FROM public.ibo_package_series m WHERE m.package_id = p.id), '[]'::jsonb)
        )
        ORDER BY p.created_at DESC
      )
      FROM public.ibo_packages p
    ), '[]'::jsonb),
    'users', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', u.id,
          'username', u.username,
          'status', CASE WHEN u.status = 'Banned' THEN 'Blocked' ELSE u.status END,
          'start_date', u.start_date,
          'expiry_date', u.expiry_date,
          'max_connections', u.max_connections,
          'notes', u.notes,
          'created_at', u.created_at,
          'subscription_id', s.id,
          'subscription_status', COALESCE(s.status, CASE WHEN u.status = 'Banned' THEN 'Blocked' ELSE u.status END),
          'package_id', s.package_id,
          'package_name', p.name,
          'subscription_expiry_date', COALESCE(s.expiry_date, u.expiry_date),
          'subscription_notes', s.notes,
          'device_count', (SELECT COUNT(*) FROM public.ibo_devices d WHERE d.user_id = u.id),
          'playlist_url', ip.public_url,
          'playlist_generated_at', ip.generated_at,
          'playlist_channel_count', ip.channel_count
        )
        ORDER BY u.created_at DESC
      )
      FROM public.iptv_users u
      LEFT JOIN public.ibo_user_subscriptions s ON s.user_id = u.id
      LEFT JOIN public.ibo_packages p ON p.id = s.package_id
      LEFT JOIN public.ibo_playlists ip ON ip.user_id = u.id
    ), '[]'::jsonb),
    'subscriptions', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', s.id,
          'user_id', s.user_id,
          'username', u.username,
          'package_id', s.package_id,
          'package_name', p.name,
          'status', s.status,
          'expiry_date', s.expiry_date,
          'max_connections', s.max_connections,
          'notes', s.notes,
          'created_at', s.created_at,
          'updated_at', s.updated_at
        )
        ORDER BY s.updated_at DESC
      )
      FROM public.ibo_user_subscriptions s
      LEFT JOIN public.iptv_users u ON u.id = s.user_id
      LEFT JOIN public.ibo_packages p ON p.id = s.package_id
    ), '[]'::jsonb),
    'playlists', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'user_id', p.user_id,
          'username', p.username,
          'bucket_name', p.bucket_name,
          'storage_path', p.storage_path,
          'public_url', p.public_url,
          'channel_count', p.channel_count,
          'generated_at', p.generated_at,
          'updated_at', p.updated_at
        )
        ORDER BY p.generated_at DESC
      )
      FROM public.ibo_playlists p
    ), '[]'::jsonb),
    'settings', jsonb_build_object(
      'app_name', COALESCE(settings_map->>'app_name', 'OMAR IBO PANEL'),
      'logo_url', COALESCE(settings_map->>'logo_url', ''),
      'api_base_url', COALESCE(settings_map->>'api_base_url', ''),
      'default_epg_url', COALESCE(settings_map->>'default_epg_url', ''),
      'theme_mode', COALESCE(settings_map->>'theme_mode', 'system'),
      'primary_color', COALESCE(settings_map->>'primary_color', '#6D4CFF'),
      'secondary_color', COALESCE(settings_map->>'secondary_color', '#1ec8a5'),
      'maintenance_mode', COALESCE((settings_map->>'maintenance_mode')::boolean, false),
      'notifications_enabled', COALESCE((settings_map->>'notifications_enabled')::boolean, true)
    ),
    'logs', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', l.id,
          'action', l.action,
          'entity_type', l.entity_type,
          'entity_id', l.entity_id,
          'message', l.message,
          'created_at', l.created_at
        )
        ORDER BY l.created_at DESC
      )
      FROM (
        SELECT * FROM public.ibo_activity_logs ORDER BY created_at DESC LIMIT 20
      ) l
    ), '[]'::jsonb),
    'content', jsonb_build_object(
      'live', COALESCE((
        SELECT jsonb_agg(
          jsonb_build_object(
            'id', s.id,
            'name', s.name,
            'logo_url', s.logo_url,
            'category_name', COALESCE(c.name, 'Live TV')
          )
          ORDER BY s.sort_order ASC, s.id ASC
        )
        FROM public.live_streams s
        LEFT JOIN public.live_categories c ON c.id = s.category_id
        WHERE s.status = 'Active'
      ), '[]'::jsonb),
      'vod', COALESCE((
        SELECT jsonb_agg(
          jsonb_build_object(
            'id', v.id,
            'title', v.title,
            'poster_url', v.poster_url,
            'category_name', COALESCE(c.name, 'Movies')
          )
          ORDER BY v.sort_order ASC, v.id ASC
        )
        FROM public.vod_streams v
        LEFT JOIN public.vod_categories c ON c.id = v.category_id
        WHERE v.status = 'Active'
      ), '[]'::jsonb),
      'series', COALESCE((
        SELECT jsonb_agg(
          jsonb_build_object(
            'id', s.id,
            'title', s.title,
            'poster_url', s.poster_url,
            'category_name', COALESCE(c.name, 'Series')
          )
          ORDER BY s.sort_order ASC, s.id ASC
        )
        FROM public.series s
        LEFT JOIN public.series_categories c ON c.id = s.category_id
        WHERE s.status = 'Active'
      ), '[]'::jsonb)
    )
  );
END;
$function$;
